# This is an example configuration to enable detect-secrets in the pre-commit hook.
# Add this file to the root folder of your repository.
#
# Read pre-commit hook framework https://pre-commit.com/ for more details about the structure of config yaml file and how git pre-commit would invoke each hook.
#
# This line indicates we will use the hook from ibm/detect-secrets to run scan during committing phase.
repos:
  # - repo: https://github.com/ibm/detect-secrets
  #   # If you desire to use a specific version of detect-secrets, you can replace `master` with other git revisions such as branch, tag or commit sha.
  #   # You are encouraged to use static refs such as tags, instead of branch name
  #   #
  #   # Running "pre-commit autoupdate" automatically updates rev to latest tag
  #   rev: 0.13.1+ibm.62.dss
  #   hooks:
  #     - id: detect-secrets # pragma: whitelist secret
  #       # Add options for detect-secrets-hook binary. You can run `detect-secrets-hook --help` to list out all possible options.
  #       # You may also run `pre-commit run detect-secrets` to preview the scan result.
  #       # when "--baseline" without "--use-all-plugins", pre-commit scan with just plugins in baseline file
  #       # when "--baseline" with "--use-all-plugins", pre-commit scan with all available plugins
  #       # add "--fail-on-unaudited" to fail pre-commit for unaudited potential secrets
  #       args: [--baseline, .secrets.baseline, --use-all-plugins]
        

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   # Ruff version.
  #   rev: v0.9.2
  #   hooks:
  #     # Run the linter.
  #     - id: ruff
  #       args: [ --fix ]
  #     # Run the formatter.
  #     - id: ruff-format

  # - repo: https://github.com/hadolint/hadolint
  #   rev: v2.12.0
  #   hooks:
  #     - id: hadolint

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.0
    hooks:
      - id: codespell
        types_or: [python, rst, markdown, cython, c]
        additional_dependencies: [tomli]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: 'docs/.*|\.*.lock|'
    - id: check-ast
    -   id: end-of-file-fixer
        exclude_types:
          - svg
    -   id: debug-statements
    # TODO: Fix this
    # -   id: name-tests-test

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        stages: [pre-commit]
      - id: isort
        name: isort (pyi)
        types: [pyi]
        stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black
        stages: [pre-commit]
        language: python
  - repo: https://github.com/kynan/nbstripout/
    rev: 0.8.1
    hooks:
      - id: nbstripout
